{{- $secretName := include "hyperpod-ray-endpoint-operator.resourceName" (dict "suffix" "extensionapi-jwt-secret" "context" $) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: extensionapi-jwt
    component: security
  name: {{ $secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
