apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    internal.operator/target-namespace: kube-system
  name: {{ include "hyperpod-ray-endpoint-operator.resourceName" (dict "suffix" "auth-reader" "context" $) }}
  namespace: {{ index .Values.rbac.roleNamespaces "auth-reader" | default "kube-system" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ include "hyperpod-ray-endpoint-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
