apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "hyperpod-ray-endpoint-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: security
  name: {{ include "hyperpod-ray-endpoint-operator.resourceName" (dict "suffix" "jwt-secrets-reader-binding" "context" $) }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hyperpod-ray-endpoint-operator.resourceName" (dict "suffix" "jwt-secrets-reader" "context" $) }}
subjects:
- kind: ServiceAccount
  name: {{ include "hyperpod-ray-endpoint-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
